[project]
name = "genomic_vision"
version = "0.1.0"

[tool.setuptools]
packages = ["src"]

dependencies = [
    "torch",
    "numpy",
    "transformers",
    "accelerate",
    "evaluate",
    "scikit-learn",
    "datasets"
]