[project]
name = "genomic_vision"
version = "0.1.0"

dependencies = [
    "torch",
    "numpy",
    "transformers",
    "accelerate",
    "evaluate",
    "scikit-learn",
    "datasets",
    "torchvision"
]

[tool.setuptools]
packages = ["src"]